-- Nim Dvir link shortener
-- Applied to an existing Supabase project with isolated table names.
-- If SHORTENER_ADMIN_SECRET changes, replace the SHA-256 hash in every admin policy.

create table if not exists public.short_links (
  id bigint generated by default as identity primary key,
  slug text not null unique check (slug ~ '^[a-z0-9][a-z0-9_-]{0,47}$'),
  destination_url text not null check (destination_url ~ '^https?://'),
  title text,
  is_active boolean not null default true,
  click_count bigint not null default 0 check (click_count >= 0),
  last_clicked_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.short_link_clicks (
  id bigint generated by default as identity primary key,
  link_id bigint not null references public.short_links(id) on delete cascade,
  clicked_at timestamptz not null default now(),
  referrer text,
  user_agent text,
  device_type text,
  browser text,
  os text,
  country text,
  region text,
  city text
);

create index if not exists short_link_clicks_link_id_idx on public.short_link_clicks(link_id);
create index if not exists short_link_clicks_clicked_at_idx on public.short_link_clicks(clicked_at desc);

alter table public.short_links enable row level security;
alter table public.short_link_clicks enable row level security;

revoke all on table public.short_links from anon, authenticated;
revoke all on table public.short_link_clicks from anon, authenticated;
grant select, insert, update, delete on table public.short_links to anon;
grant select, insert on table public.short_link_clicks to anon;
grant usage, select on sequence public.short_links_id_seq to anon;
grant usage, select on sequence public.short_link_clicks_id_seq to anon;

drop policy if exists "short links public resolve" on public.short_links;
create policy "short links public resolve"
on public.short_links for select to anon
using (is_active = true);

drop policy if exists "short links admin read" on public.short_links;
create policy "short links admin read"
on public.short_links for select to anon
using (
  encode(
    extensions.digest(
      convert_to(coalesce((current_setting('request.headers', true)::jsonb ->> 'x-shortener-admin'), ''), 'UTF8'),
      'sha256'
    ),
    'hex'
  ) = '30143d1ccbee4bf1b551667cb6c4c5b5ab1c11e7b59fc95dc1a27b432fdc51b4'
);

drop policy if exists "short links admin insert" on public.short_links;
create policy "short links admin insert"
on public.short_links for insert to anon
with check (
  encode(
    extensions.digest(
      convert_to(coalesce((current_setting('request.headers', true)::jsonb ->> 'x-shortener-admin'), ''), 'UTF8'),
      'sha256'
    ),
    'hex'
  ) = '30143d1ccbee4bf1b551667cb6c4c5b5ab1c11e7b59fc95dc1a27b432fdc51b4'
);

drop policy if exists "short links admin update" on public.short_links;
create policy "short links admin update"
on public.short_links for update to anon
using (
  encode(
    extensions.digest(
      convert_to(coalesce((current_setting('request.headers', true)::jsonb ->> 'x-shortener-admin'), ''), 'UTF8'),
      'sha256'
    ),
    'hex'
  ) = '30143d1ccbee4bf1b551667cb6c4c5b5ab1c11e7b59fc95dc1a27b432fdc51b4'
)
with check (
  encode(
    extensions.digest(
      convert_to(coalesce((current_setting('request.headers', true)::jsonb ->> 'x-shortener-admin'), ''), 'UTF8'),
      'sha256'
    ),
    'hex'
  ) = '30143d1ccbee4bf1b551667cb6c4c5b5ab1c11e7b59fc95dc1a27b432fdc51b4'
);

drop policy if exists "short links admin delete" on public.short_links;
create policy "short links admin delete"
on public.short_links for delete to anon
using (
  encode(
    extensions.digest(
      convert_to(coalesce((current_setting('request.headers', true)::jsonb ->> 'x-shortener-admin'), ''), 'UTF8'),
      'sha256'
    ),
    'hex'
  ) = '30143d1ccbee4bf1b551667cb6c4c5b5ab1c11e7b59fc95dc1a27b432fdc51b4'
);

drop policy if exists "short link clicks public insert" on public.short_link_clicks;
create policy "short link clicks public insert"
on public.short_link_clicks for insert to anon
with check (
  exists (
    select 1
    from public.short_links
    where short_links.id = short_link_clicks.link_id
      and short_links.is_active = true
  )
);

drop policy if exists "short link clicks admin read" on public.short_link_clicks;
create policy "short link clicks admin read"
on public.short_link_clicks for select to anon
using (
  encode(
    extensions.digest(
      convert_to(coalesce((current_setting('request.headers', true)::jsonb ->> 'x-shortener-admin'), ''), 'UTF8'),
      'sha256'
    ),
    'hex'
  ) = '30143d1ccbee4bf1b551667cb6c4c5b5ab1c11e7b59fc95dc1a27b432fdc51b4'
);

create schema if not exists shortener_private;
revoke all on schema shortener_private from public, anon, authenticated;

create or replace function shortener_private.rollup_click()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.short_links
  set click_count = click_count + 1,
      last_clicked_at = new.clicked_at
  where id = new.link_id;
  return new;
end;
$$;

revoke all on function shortener_private.rollup_click() from public, anon, authenticated;

drop trigger if exists short_link_click_rollup on public.short_link_clicks;
create trigger short_link_click_rollup
after insert on public.short_link_clicks
for each row execute function shortener_private.rollup_click();
